accounts/urls.py
from django.urls import path, include
# this will allow me to use the new features of LoginView and LogoutView of django, so easy!
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),

]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('(?P<username>[-\w]+)/', views.PostList.as_view(), name='all'),
    path('new/', views.CreatePost.as_view(), name='create'),
    path('by/(?P<username>[-\w]+)/', views.UserPosts.as_view(), name='for_user'),
    path('by/(?P<username>[-\w]+)/(?P<pk>\d+)/', views.PostDetail.as_view(), name='single'),
    path('delete/(?P<pk>\d+)/', views.DeletePost.as_view(), name='delete'),

]

socialmedia_project/urls.py
from django.contrib import admin
from django.urls import path, include
from socialmedia_project import views
from posts import views as v

urlpatterns = [
    path('', views.HomePage.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')), # to allow us to connect for authorization
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
    path('posts/', include("posts.urls", namespace="posts")),
    path('groups/',include("groups.urls", namespace="groups")),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <!-- Bootstrap 4.5.2 -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <meta charset="utf-8">
    <title>Star Social</title>
    <!-- Font Awesome for Icons   -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Alternative to Bootstrap 3 Glyphicons -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'socialmedia_project/css/master.css' %}">

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat+Subrayada&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
  </head>
  <body>

    <!-- <nav class='navbar mynav' role='navigation' id='navbar'>
      <div class="container">
        <a class='navbar-brand mynav' href="{% url 'home' %}">Star Social</a>
        <ul class='nav navbar-nav navbar-right'>
          {% if user.is_authenticated %}
            <li><a href="#">Post</a></li>
            <li><a href="#">Groups</a></li>
            <li><a href="#">Create Group</a></li>
            <li><a href="{% url 'accounts:logout' %}">Log Out</a></li>
          {% else %}
            <li><a href="#">Groups</a></li>
            <li><a href="{% url 'accounts:login' %}">Log In</a></li>
            <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>
          {% endif %}
        </ul>
      </div>
    </nav> -->

    <nav class="navbar navbar-expand-lg navbar-light bg-light techfont">
      <div class="container-fluid">

        {% if user.is_authenticated %}
        <a style="font-size:1.7em;" class="navbar-brand bigbrand" href="{% url 'posts:all' username=user.username %}"><span class="far fa-star-half"></span>StarSocial</a>
        {% else %}
        <a style="font-size:1.7em;" class="navbar-brand bigbrand" href="{% url 'home' %}"><span class="far fa-star-half"></span>StarSocial</a>
        {% endif %}

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'posts:create' %}">Posts</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'groups:all' %}">Groups</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'groups:create' %}">Create Group</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'accounts:logout' %}">Log Out</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'accounts:login' %}">Log In</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'accounts:signup' %}">Sign Up</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    <div style="margin-top:20px;" class="container">
      {% block content %}

      {% endblock %}
    </div>

    <canvas id="canvas"></canvas>

    <script src="{% static "socialmedia_project/js/master.js"%}" type="text/javascript" ></script>

    <!-- Latest compiled and minified jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

templates/index.html
{% extends "base.html" %}

{% block content %}
<!DOCTYPE html>
<h1> Welcome to Star Social!</h1>
{% endblock %}

templates/test.html
{% extends 'base.html' %}

{% block content %}
<h1>You are now logged in!</h1>
{% endblock %}

templates/thanks.html
{% extends 'base.html' %}

{% block content %}
<h1>Thanks for visiting, come back soon!</h1>
{% endblock %}